### ISSUE TITLE
Unable to run showcase

### ISSUE THREAD

**Issue by Zambrella** [astonbitecode/j4rs-showcase#1]
Hi 👋 

I was having issues running my own `j4rs` project so I thought I'd try your showcase.

`cargo run` runs fine but when selecting an option of `f` or `n` I get the following error:

```
Exception in thread "main" org.astonbitecode.j4rs.errors.InvocationException: While invoking method setCallbackToApplicationAndLaunch of Class org.astonbitecode.j4rs.api.jfx.FxApplicationStartCallback
	at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invoke(JsonInvocationImpl.java:73)
	at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeToChannel(JsonInvocationImpl.java:103)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeMethod(JsonInvocationImpl.java:184)
	at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invoke(JsonInvocationImpl.java:70)
	... 1 more
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.astonbitecode.j4rs.api.jfx.FxApplicationStartCallback.setCallbackToApplicationAndLaunch(FxApplicationStartCallback.java:22)
	... 7 more
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 17 more
Error: JavaError("An Exception was thrown by Java... Please check the logs or the console.")
```

I'm running on `MacOS 13.1`.
`java --version` outputs
```
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
OpenJDK 64-Bit Server VM (build 11.0.13+0-b1751.21-8125866, mixed mode)
```

Many thanks from a `Rust` and `Java` novice.

**Comment by astonbitecode** [comment]
I hit something similar (getting `panics` after updating my local rust-std version) and what helped was to do a `cargo clean` before `cargo run`. 

The error that you get, shows that the initialization of `j4rs` is not done correctly because the classpath is corrupted (the jars for javafx are not found/loaded).

**Comment by Zambrella** [comment]
I'm afraid I'm still getting the same error after a `cargo clean`.

I managed to get my own application working though :)

**Comment by astonbitecode** [comment]
Hmm, this is weird. Can you also try a `cargo update`? Something like:

`cargo clean && cargo update && cargo run`

Also, what are the contents of your `target/debug/jassets`?

**Comment by Zambrella** [comment]
Still no luck running those commands.

Contents of `target/debug/jassets`
![Screenshot 2023-02-08 at 12 58 54](https://user-images.githubusercontent.com/53582591/217536307-3789299c-ee07-4b0e-b3e9-f03722468790.png)


Also, this may be a bit of a long shot but I'm attempting to get Rust code to work in Flutter (Dart). I have been using [flutter_rust_bridge](https://cjycode.com/flutter_rust_bridge/index.html) and it works well until I call `JvmBuilder::new()` and I get a permission denied error. Is this just fundamentally not going to work or do I need to look into the "Portability assumptions after Rust build (shipping a j4rs application)" section of the j4rs README?

**Comment by astonbitecode** [comment]
The issue that you face, is that the javafx classes are not in the classpath. Specifically, j4rs complains that the class `javafx.application.Application`.

The list of the files of your jassets are not complete. It seems that they do not contain the actual implementations and classes of javafx. In my Linux I have the following in jassets:

>j4rs-0.15.3-SNAPSHOT-jar-with-dependencies.jar  javafx-fxml-13.0.2-linux.jar
>javafx-base-13.0.2.jar                          javafx-graphics-13.0.2.jar
>javafx-base-13.0.2-linux.jar                    javafx-graphics-13.0.2-linux.jar
>javafx-controls-13.0.2.jar                      javafx-media-13.0.2.jar
>javafx-controls-13.0.2-linux.jar                javafx-media-13.0.2-linux.jar
>javafx-fxml-13.0.2.jar

As you can see, there are some "*-linux.jar" files. These files are the ones that contain the classes needed. For example, `javafx.application.Application` class is in `javafx-graphics-13.0.2-linux.jar`. The `javafx-graphics-13.0.2.jar` (without the `-linux`) contains only a _Manifest_ file.

I don't run Macos, so I cannot know if there are pecularities there, but I was able to reproduce this in windows. There, I have files as you (no`-windows`) whatsoever. 

I will need to check with `j4rs` code for that. Apparently there is a problem there.

**Comment by astonbitecode** [comment]
Ok got it. It seems that there are no `-windows` jars... The qualifiers used by j4rs are wrong. we need `-win` for windows and `-mac` for macos...

You may see the available jars [here](https://repo.maven.apache.org/maven2/org/openjfx/javafx-fxml/13.0.2/)

I will impl a fix for `j4rs`.

Thanks for noticing this.

**Comment by Zambrella** [comment]
No problem, glad I could help. Let me know if you want me to test anything on MacOS. Thanks for the quick responses :)

**Comment by astonbitecode** [comment]
I pushed a fix for `j4rs` to address the classifiers issue. 

Can you please see if all the jars are in your jassets after doing a `cargo update`?

**Comment by Zambrella** [comment]
![Screenshot 2023-02-09 at 10 55 10](https://user-images.githubusercontent.com/53582591/217793383-4a8e34fb-2a62-49e7-ac02-2f2c30553749.png)

There are no errors when pressing `f` or `n` but nothing actually happens.

**Comment by astonbitecode** [comment]
Good, so the jars seem fine now. Let's continue with debugging. Please do clean and update, then run with enabled console logging in j4rs and provide the output:

`J4RS_CONSOLE_LOG_LEVEL=debug cargo run`

**Comment by Zambrella** [comment]
```
warning: javafx dependencies deployment completed...
    Finished dev [unoptimized + debuginfo] target(s) in 22.54s
     Running `target/debug/javafx-from-rust`
Welcome! Please select an option and hit enter:
f: Launch a JavaFX UI built with FXML
n: Launch a JavaFX UI built with code
n
INFO: Setting classpath to -Djava.class.path=/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/jassets/j4rs-0.15.3-SNAPSHOT-jar-with-dependencies.jar:/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/jassets/javafx-graphics-13.0.2-mac.jar:/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/jassets/javafx-media-13.0.2-mac.jar:/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/jassets/javafx-base-13.0.2-mac.jar:/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/jassets/javafx-fxml-13.0.2-mac.jar:/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/jassets/javafx-media-13.0.2.jar:/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/jassets/javafx-controls-13.0.2-mac.jar:/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/jassets/javafx-graphics-13.0.2.jar:/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/jassets/javafx-controls-13.0.2.jar:/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/jassets/javafx-fxml-13.0.2.jar:/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/jassets/javafx-base-13.0.2.jar
INFO: Setting library path to -Djava.library.path=/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/deps:/usr/lib:/lib
INFO: Passing to the Java world the name of the library to load: j4rs-deb1b91d118def8f
DEBUG: Creating a Jvm
INFO: No JVMs exist. Creating a new one...
DEBUG: Called set_jni_get_method_id
DEBUG: Called set_jni_get_static_method_id
DEBUG: Called set_jni_new_object
DEBUG: Called set_jni_new_string_utf
DEBUG: Called set_jni_get_string_utf_chars
DEBUG: Called set_jni_release_string_utf_chars
DEBUG: Called set_jni_call_object_method
DEBUG: Called set_jni_call_byte_method
DEBUG: Called set_jni_call_short_method
DEBUG: Called set_jni_call_int_method
DEBUG: Called set_jni_call_long_method
DEBUG: Called set_jni_call_float_method
DEBUG: Called set_jni_call_double_method
DEBUG: Called set_jni_call_void_method
DEBUG: Called set_jni_call_static_object_method
DEBUG: Called set_jni_new_object_array
DEBUG: Called set_jni_set_object_array_element
DEBUG: Called set_jni_exception_check
DEBUG: Called set_jni_exception_describe
DEBUG: Called set_jni_exception_clear
DEBUG: Called set_jni_delete_local_ref
DEBUG: Called set_jni_delete_global_ref
DEBUG: Called set_jni_new_global_ref
DEBUG: Called set_jni_throw_new
DEBUG: Called set_is_same_object
DEBUG: Called set_thread_local_env
DEBUG: Initializing NativeCallbackSupport with libname j4rs-deb1b91d118def8f
DEBUG: Invoking static method initialize of class org.astonbitecode.j4rs.api.invocation.NativeCallbackToRustChannelSupport using 1 arguments
DEBUG: Called set_factory_class
DEBUG: Called set_factory_create_for_static_method
DEBUG: Called set_invocation_arg_class
DEBUG: Creating jobject from Rust basic for class java.lang.String
DEBUG: Calling the InvocationArg constructor with 'java.lang.String'
DEBUG: Called set_inv_arg_basic_rust_constructor_method
DEBUG: Called set_java_instance_class
DEBUG: Called set_invoke_static_method
DEBUG: Dropping an instance of known_in_java_world
DEBUG: Dropping an instance of java.lang.String
DEBUG: NativeCallbackSupport initialized
DEBUG: Instantiating class org.astonbitecode.j4rs.api.jfx.FxApplicationStartCallback using 0 arguments
DEBUG: Called set_factory_instantiate_method
DEBUG: Invoking method setCallbackToApplicationAndLaunch of class org.astonbitecode.j4rs.api.jfx.FxApplicationStartCallback using 0 arguments. The result of the invocation will come via an InstanceReceiver
DEBUG: Called set_invoke_to_channel_method
DEBUG: Dropping an instance of org.astonbitecode.j4rs.api.jfx.FxApplicationStartCallback
```

and

```
╰─➤  J4RS_CONSOLE_LOG_LEVEL=debug cargo run                                                                                                                                                                                                              130 ↵
warning: javafx dependencies deployment...
warning: javafx dependencies deployment completed...
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/javafx-from-rust`
Welcome! Please select an option and hit enter:
f: Launch a JavaFX UI built with FXML
n: Launch a JavaFX UI built with code
f
INFO: Setting classpath to -Djava.class.path=/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/jassets/j4rs-0.15.3-SNAPSHOT-jar-with-dependencies.jar:/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/jassets/javafx-graphics-13.0.2-mac.jar:/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/jassets/javafx-media-13.0.2-mac.jar:/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/jassets/javafx-base-13.0.2-mac.jar:/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/jassets/javafx-fxml-13.0.2-mac.jar:/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/jassets/javafx-media-13.0.2.jar:/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/jassets/javafx-controls-13.0.2-mac.jar:/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/jassets/javafx-graphics-13.0.2.jar:/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/jassets/javafx-controls-13.0.2.jar:/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/jassets/javafx-fxml-13.0.2.jar:/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/jassets/javafx-base-13.0.2.jar
INFO: Setting library path to -Djava.library.path=/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/deps:/usr/lib:/lib
INFO: Passing to the Java world the name of the library to load: j4rs-deb1b91d118def8f
DEBUG: Creating a Jvm
INFO: No JVMs exist. Creating a new one...
DEBUG: Called set_jni_get_method_id
DEBUG: Called set_jni_get_static_method_id
DEBUG: Called set_jni_new_object
DEBUG: Called set_jni_new_string_utf
DEBUG: Called set_jni_get_string_utf_chars
DEBUG: Called set_jni_release_string_utf_chars
DEBUG: Called set_jni_call_object_method
DEBUG: Called set_jni_call_byte_method
DEBUG: Called set_jni_call_short_method
DEBUG: Called set_jni_call_int_method
DEBUG: Called set_jni_call_long_method
DEBUG: Called set_jni_call_float_method
DEBUG: Called set_jni_call_double_method
DEBUG: Called set_jni_call_void_method
DEBUG: Called set_jni_call_static_object_method
DEBUG: Called set_jni_new_object_array
DEBUG: Called set_jni_set_object_array_element
DEBUG: Called set_jni_exception_check
DEBUG: Called set_jni_exception_describe
DEBUG: Called set_jni_exception_clear
DEBUG: Called set_jni_delete_local_ref
DEBUG: Called set_jni_delete_global_ref
DEBUG: Called set_jni_new_global_ref
DEBUG: Called set_jni_throw_new
DEBUG: Called set_is_same_object
DEBUG: Called set_thread_local_env
DEBUG: Initializing NativeCallbackSupport with libname j4rs-deb1b91d118def8f
DEBUG: Invoking static method initialize of class org.astonbitecode.j4rs.api.invocation.NativeCallbackToRustChannelSupport using 1 arguments
DEBUG: Called set_factory_class
DEBUG: Called set_factory_create_for_static_method
DEBUG: Called set_invocation_arg_class
DEBUG: Creating jobject from Rust basic for class java.lang.String
DEBUG: Calling the InvocationArg constructor with 'java.lang.String'
DEBUG: Called set_inv_arg_basic_rust_constructor_method
DEBUG: Called set_java_instance_class
DEBUG: Called set_invoke_static_method
DEBUG: Dropping an instance of known_in_java_world
DEBUG: Dropping an instance of java.lang.String
DEBUG: NativeCallbackSupport initialized
DEBUG: Instantiating class org.astonbitecode.j4rs.api.jfx.FxApplicationStartCallback using 0 arguments
DEBUG: Called set_factory_instantiate_method
DEBUG: Invoking method setCallbackToApplicationAndLaunch of class org.astonbitecode.j4rs.api.jfx.FxApplicationStartCallback using 0 arguments. The result of the invocation will come via an InstanceReceiver
DEBUG: Called set_invoke_to_channel_method
DEBUG: Dropping an instance of org.astonbitecode.j4rs.api.jfx.FxApplicationStartCallback
```

**Comment by astonbitecode** [comment]
Thanks. It seems that your application stops at the time the callbacks from Java are getting initialized.

Do you have a `libj4rs.so` under the `deps` directory? As you also mentioned, you may look into [j4rs portability assumptions](https://github.com/astonbitecode/j4rs#portability-assumptions-after-rust-build-shipping-a-j4rs-application)

**Comment by Zambrella** [comment]
There is no `libj4rs.so` under `target/debug/deps/`.

**Comment by astonbitecode** [comment]
As shown in the logs you provided, 

>INFO: Setting library path to -Djava.library.path=/Users/douglastodd/development_code/java/j4rs-showcase/target/debug/deps:/usr/lib:/lib
>INFO: Passing to the Java world the name of the library to load: j4rs-deb1b91d118def8f

`j4rs` attempts to load the shared library named `libj4rs-deb1b91d118def8f.so`. Does the application process have access to this file?

**Comment by Zambrella** [comment]
Where would you expect the library `libj4rs-deb1b91d118def8f.so` to be on the system?

**Comment by astonbitecode** [comment]
Two directories are needed for j4rs to work: **jassets** and **deps**.

* **jassets** contains the j4rs jar and other jars that may be deployed using Maven.
* **deps** should contain the j4rs dynamic library (libj4rs-deb1b91d118def8f.so in your case). This is needed to achieve callbacks from java to rust.

These directories must lay inside the same directory (aka [base_path](https://github.com/astonbitecode/j4rs#portability-assumptions-after-rust-build-shipping-a-j4rs-application)) and by default, in a development setup, a `cargo build` creates them under `target/debug/`. The created application lies in there too.

The directory tree is:

```
/j4rs-showcase
    |
    + --- target
            |
            + --- jassets/
            + --- deps/
            + --- myapp (executable)
```

Your app should be executed with permissions that allow accessing these directories. 

I am not sure what you are trying to achieve, since you mentioned `flutter_rust_bridge` and I haven't used flutter.
I also don't own a mac and therefore I cannot further debug... Did you try to run the showcase as a standalone project in mac?

**Comment by Zambrella** [comment]
I think there's been some confusion.

I've got j4rs working in my app, however, the error I'm getting is when running the showcase app.

Do I need anything extra apart from Java installed for running a JavaFX app?
