### ISSUE TITLE
Unable to load jars (MaterialFX)

### ISSUE THREAD

**Issue by PineberryCode** [astonbitecode/j4rs-showcase#2]
Hello

I had some issues when I wanted load **materialfx.jar** and others **.jar**:
```
Exception in thread "JavaFX Application Thread" org.astonbitecode.j4rs.errors.InvocationException: Error while invoking method loadFxml of Class org.astonbitecode.j4rs.api.jfx.J4rsFxmlLoader
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeStatic(JsonInvocationImpl.java:87)
        at org.astonbitecode.j4rs.api.invocation.JavaFxInvocation.lambda$invokeStatic$1(JavaFxInvocation.java:52)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeMethod(JsonInvocationImpl.java:198)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeStatic(JsonInvocationImpl.java:82)
        ... 8 more
Caused by: javafx.fxml.LoadException: 
/home/cube/Documentos/delete/vscode/github/pyramo/./src/view/login.fxml

        at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2625)
        at javafx.fxml.FXMLLoader.importClass(FXMLLoader.java:2863)
        at javafx.fxml.FXMLLoader.processImport(FXMLLoader.java:2707)
        at javafx.fxml.FXMLLoader.processProcessingInstruction(FXMLLoader.java:2676)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2542)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2435)
        at org.astonbitecode.j4rs.api.jfx.J4rsFxmlLoader.loadFxml(J4rsFxmlLoader.java:43)
        ... 14 more
Caused by: java.lang.ClassNotFoundException: io.github.palexdev.materialfx.controls.MFXButton
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at javafx.fxml.FXMLLoader.loadTypeForPackage(FXMLLoader.java:2931)
        at javafx.fxml.FXMLLoader.loadType(FXMLLoader.java:2920)
        at javafx.fxml.FXMLLoader.importClass(FXMLLoader.java:2861)
        ... 20 more
```

I believe that I have successfully loaded the `JAR` files in `build.rs`, although it's possible that I have guided badly with the [documentation](https://crates.io/crates/j4rs/0.1.0).
- - -
It's my `build.rs`:
```Rust
fn main() {
    let root = "/home/cube/Documentos/delete/vscode/github/pyramo";

    let materialfx_path = format!("{}/materialfx-11.17.0.jar", root);
    let mfxcore_path = format!("{}/mfxcore-11.8.0.jar", root);
    let mfxeffects_path = format!("{}/mfxeffects-11.3.0.jar", root);
    let mfxlocalization_path = format!("{}/mfxlocalization-11.1.0.jar", root);
    let mfxresources_path = format!("{}/mfxresources-11.9.1.jar", root);
    let virtualizedfx_path = format!("{}/virtualizedfx-11.9.6.jar", root);
    let javafx_base_21_linux = format!("{}/javafx-base-21-linux.jar", root);
    let javafx_base_21 = format!("{}/javafx-base-21.jar", root);
    let javafx_controls_21_linux = format!("{}/javafx-controls-21-linux.jar", root);
    let javafx_controls_21 = format!("{}/javafx-controls-21.jar", root);
    let javafx_fxml_21_linux = format!("{}/javafx-fxml-21-linux.jar", root);
    let javafx_fxml_21 = format!("{}/javafx-fxml-21.jar", root);
    let javafx_graphics_21_linux = format!("{}/javafx-graphics-21-linux.jar", root);
    let javafx_graphics_21 = format!("{}/javafx-graphics-21.jar", root);

    let classpath_materialfx = ClasspathEntry::new(&materialfx_path);
    let classpath_mfxcore = ClasspathEntry::new(&mfxcore_path);
    let classpath_mfxeffects = ClasspathEntry::new(&mfxeffects_path);
    let classpath_mfxlocalization = ClasspathEntry::new(&mfxlocalization_path);
    let classpath_mfxresources = ClasspathEntry::new(&mfxresources_path);
    let classpath_virtualizedfx = ClasspathEntry::new(&virtualizedfx_path);
    let classpath_javafx_base_21_linux = ClasspathEntry::new(&javafx_base_21_linux);
    let classpath_javafx_base_21 = ClasspathEntry::new(&javafx_base_21);
    let classpath_javafx_controls_21_linux = ClasspathEntry::new(&javafx_controls_21_linux);
    let classpath_javafx_controls_21 = ClasspathEntry::new(&javafx_controls_21);
    let classpath_javafx_fxml_21_linux = ClasspathEntry::new(&javafx_fxml_21_linux);
    let classpath_javafx_fxml_21 = ClasspathEntry::new(&javafx_fxml_21);
    let classpath_javafx_graphics_21_linux = ClasspathEntry::new(&javafx_graphics_21_linux);
    let classpath_javafx_graphics_21 = ClasspathEntry::new(&javafx_graphics_21);

    let jars = vec![
        classpath_materialfx,
        classpath_mfxcore,
        classpath_mfxeffects,
        classpath_mfxlocalization,
        classpath_mfxresources,
        classpath_virtualizedfx,
        classpath_javafx_base_21_linux,
        classpath_javafx_base_21,
        classpath_javafx_controls_21_linux,
        classpath_javafx_controls_21,
        classpath_javafx_fxml_21_linux,
        classpath_javafx_fxml_21,
        classpath_javafx_graphics_21_linux,
        classpath_javafx_graphics_21
    ];

    let jvm = JvmBuilder::new().classpath_entries(jars).build().unwrap();
    jvm.deploy_javafx_dependencies().unwrap();
}
```

**Comment by astonbitecode** [comment]
Hi,

The `ClassNotFoundException` you get, means that the class is not in the classpath. 

You are providing the classpath during build, but not during runtime. Please, try to do in your application code what you do in the build script: use a `Jvm` with the needed jars added in the classpath.

Also, since you supply yourself the classpath entries for `JavaFX`, you do not need to call `jvm.deploy_javafx_dependencies()`. Please remove this as well from your code in order to keep your classpath clean. 

If the code you share is the only thing your build script does, you do not need the build script at all.

**Comment by PineberryCode** [comment]
Thanks for quoting.
- - -
The problem has been resolved when I placed the same code in my `main.rs`.
I'm sharing my code for anyone who may have encountered the same problem:
```Rust
fn main() -> Result<()> {
    let root = "/home/cube/Documentos/delete/vscode/github/pyramo";
    let materialfx_path = format!("{}/materialfx-11.17.0.jar", root);
    let mfxcore_path = format!("{}/mfxcore-11.8.0.jar", root);
    let mfxeffects_path = format!("{}/mfxeffects-11.3.0.jar", root);
    let mfxlocalization_path = format!("{}/mfxlocalization-11.1.0.jar", root);
    let mfxresources_path = format!("{}/mfxresources-11.9.1.jar", root);
    let virtualizedfx_path = format!("{}/virtualizedfx-11.9.6.jar", root);

    let javafx_base_21_linux = format!("{}/javafx-base-21-linux.jar", root);
    let javafx_base_21 = format!("{}/javafx-base-21.jar", root);
    let javafx_controls_21_linux = format!("{}/javafx-controls-21-linux.jar", root);
    let javafx_controls_21 = format!("{}/javafx-controls-21.jar", root);
    let javafx_fxml_21_linux = format!("{}/javafx-fxml-21-linux.jar", root);
    let javafx_fxml_21 = format!("{}/javafx-fxml-21.jar", root);
    let javafx_graphics_21_linux = format!("{}/javafx-graphics-21-linux.jar", root);
    let javafx_graphics_21 = format!("{}/javafx-graphics-21.jar", root);

    let classpath_materialfx = ClasspathEntry::new(&materialfx_path);
    let classpath_mfxcore = ClasspathEntry::new(&mfxcore_path);
    let classpath_mfxeffects = ClasspathEntry::new(&mfxeffects_path);
    let classpath_mfxlocalization = ClasspathEntry::new(&mfxlocalization_path);
    let classpath_mfxresources = ClasspathEntry::new(&mfxresources_path);
    let classpath_virtualizedfx = ClasspathEntry::new(&virtualizedfx_path);

    let classpath_javafx_base_21_linux = ClasspathEntry::new(&javafx_base_21_linux);
    let classpath_javafx_base_21 = ClasspathEntry::new(&javafx_base_21);
    let classpath_javafx_controls_21_linux = ClasspathEntry::new(&javafx_controls_21_linux);
    let classpath_javafx_controls_21 = ClasspathEntry::new(&javafx_controls_21);
    let classpath_javafx_fxml_21_linux = ClasspathEntry::new(&javafx_fxml_21_linux);
    let classpath_javafx_fxml_21 = ClasspathEntry::new(&javafx_fxml_21);
    let classpath_javafx_graphics_21_linux = ClasspathEntry::new(&javafx_graphics_21_linux);
    let classpath_javafx_graphics_21 = ClasspathEntry::new(&javafx_graphics_21);

    let jars = vec![
        classpath_materialfx,
        classpath_mfxcore,
        classpath_mfxeffects,
        classpath_mfxlocalization,
        classpath_mfxresources,
        classpath_virtualizedfx,

        classpath_javafx_base_21_linux,
        classpath_javafx_base_21,
        classpath_javafx_controls_21_linux,
        classpath_javafx_controls_21,
        classpath_javafx_fxml_21_linux,
        classpath_javafx_fxml_21,
        classpath_javafx_graphics_21_linux,
        classpath_javafx_graphics_21
    ];
    
    let jvm = JvmBuilder::new()
    .classpath_entries(jars)
    
    .with_javafx_support().build()?;

    fxml(&jvm)
}

fn fxml(jvm: &Jvm) -> Result<()>  {
    let stage = jvm.start_javafx_app()?.rx().recv()?;

    /* 
     * More code...
     */

    Ok(())
}
```
